### PR TITLE
[UI Improvements] Numerous upgrades to the Register, Login, RegisterDetails, and ResetPassword forms

### PR DESCRIPTION
**Pull request by MJGrant**
- Errors now display in an Alert element, so they get a red background, ! symbol, etc 
- Fields are now marked with a red border when a form contains an error [out of scope: marking ONLY the field that has a problem as 'error'; not sure how to achieve this because the error that is thrown is a string, not something I can, for example, check for presence of a particular 'error code' on]
- Moved errors closer to the button that generates them (like right below it) instead of below links or other elements below that button
- Better error messaging when failing to log in, the message that's passed up to the UI layer is variable based on the error code received. The user should now have a better idea of what is wrong with their login attempt (ie, the message communicates "user doesn't exist" or "user exists but password is wrong") 
- Improved the presentation on very narrow and very wide screens (ie: buttons no longer stretch super wide on very wide screens, and buttons/fields use more of the available width on narrow screens)
- Made these four pages more consistent with each other in terms of looks (header size, text placement, etc.) and code (they all use the same hierarchy of grid elements now)
- More HTML form validation so there are some input-specific error indicators now (just the default "tooltip" you get for free from HTML, customizing them for this app is out of scope for this week)

### CODE REVIEW

**Comment by RebeccaLyric** [comment]
I think it looks good! Two questions: 

- Should there be an alert if the user doesn't enter anything for the display name?

- On the browser's mobile emulator it looks like the login page scrolls (see below). Is that something that doesn't happen on the iPad? And/or is it not in the scope of this PR.

Screen Shot 2020-04-29 at 8 52 38 AM

**Comment by MJGrant** [comment]
I get this HTML validation tooltip thingy if you leave the displayName blank, does it show for you?

Screenshot 2020-04-29 09 28 28

The red outline treatment is generated when the form is in error state, which is set when Firebase responds that something was wrong. Firebase doesn't have an error response for displayName being blank because that's just something we came up with, there's no Firebase error to hook into. To set the form as being in an error state because of something that's just on the UI end (not from a Firebase response) is going to require some research in how to do it and implementing something novel. 

Can we live with the HTML tooltip for midpoint? There are a couple weeks dedicated to improving this kind of UI stuff in the second half of the project.

**Comment by MJGrant** [comment]
Okay it wasn't as bad as I thought it'd be: 

Screenshot 2020-04-29 09 52 54

I blame EmberJS for teaching me that form validation is pain and suffering...

**Comment by MJGrant** [comment]
I don't know what to do about the scrolling. It happens on iPad too and it's something we should fix, but I don't know what the right answer is yet. 

My favorite idea so far (but I haven't given this a ton of thought, I was hoping to kick this into the post-Midpoint weeks) was to not show "Forgot password" and "Create account" links until the user tries to log in but fails, and then show them in a modal popup so they're only on screen when they might actually be helpful. Removing them from the form might remove enough height to get the whole thing to fit, too, but I haven't tested that theory. 

It's in my to-do list of UI fixes: 

Screenshot 2020-04-29 10 04 30

**Comment by RebeccaLyric** [comment]
Oh, cool! Hooray for it being an easy adjustment.

We definitely don't need to implement the scrolling at this point. It's something the grandparent side will need to implement too so it's something I've been thinking about. I like your idea and hopefully we can come up with some workable solutions throughout the app.

Yay for making the app more polished! It looks great :)

**Comment by MJGrant** [comment]
Screenshot 2020-04-29 10 30 23

I did the same improvements to the addAccountLink page (forgot about it in my first pass, whoops - I was testing as a receiver account!)

**Pull request merged**
