### PR TITLE
ipad/Safari fit and finish 

### PR DESCRIPTION
**Pull request by MJGrant**
Numerous fixes, including: 

**[Color palette]**
- Did a quick color pass to make everything use the light/dark blue color scheme [note: the rest of the screenshots here were taken before this work was done]

Screenshot 2020-05-28 11 27 16

**[Inbox]**
- Responsive Inbox now fits basically any screen size (let me know if you find an exception) on every device/browser combo I could test it on (Chrome/Macbook, Safari/Macbook, Safari/iPad, Chrome/iOS, Safari/iOS)
- New color palette for letters with greater distinction between read/unread
- Background color to help 'letters' pop
- New letter design that communicates more information about the letter, including the sender's name, a timestamp, and a short preview of the message (if there is one)

IMG_0298

Mobile (I know *we* aren't targeting this device but I've never worked on a website that doesn't have to fit mobile, so here it is)
IMG_2249

iPad vertical (I know we are not targeting this orientation but our users are supposed to be "tech illiterate", so I wanted the app to still be serviceable in this orientation, too):
IMG_0312
(a third one would appear in a second row, left justified)

**[Grandparent views]**
- "Grandparent" pages compacted to fit on iPad. The most notable change here is that I removed the "sub header" text which didn't seem to give any information that could not be discerned from the button choices below the box.
- Shortened many of the "grandparent button" strings for clarity and to prevent them wrapping around to two lines, the second of which was inevitably offscreen on the iPad
- Added "Reply with..." optional string (showReplyWith) on GrandparentLayout that is only used when viewing the post as a grandparent 
- The buttons go to 100% width and stack on mobile
- Removed the border for a cleaner presentation, maybe just my personal dislike of outlines showing here but I thought it looked better without 

IMG_2251

**[Grandparent, Emoji reply]** 
- Fixed a bug with the emoji replies not displaying to the "Family Member" the same ones you picked on the "Grandparent" side (ie: if you replied with just a 'bandaid', you'd get a smiley on the other end)
- Fixed the band-aid graphic flicker, the .png wasn't base64 for [reasons unknown] but re-exporting it from Photoshop fixed the flicker
- Changed the "selected emoji" highlight to blue instead of black, because the black/darkened highlighting looked more like the user was disabling the ones they were picking
- Made it so the "Send" button is disabled on the emoji reply page when no Emoji are selected to be consistent with the message reply page and to avoid having to pop an alert which pushes things off-screen on iPad

IMG_0293

**[Voice reply page]**
- Compacted the Voice Reply page and moved the "too much text" warning below the textbox so the text box does not get moved down when it appears, also to be consistent with the character limit display on the "Family member" side 
- Fixed the weird oval-shaped button effect that only happened in Safari
- Made the button more square to be like other buttons in the app for a more consistent button language

**[Grandparent 'reply sent' page]**
- Removed the redundant display of what was just sent; I thought it was confusing to see an exact copy of what you just sent and have to take another action to advance so I replaced it with an animated envelope to help sell the idea that a reply was "sent" and the action is complete

IMG_0294

**[Misc]**
- Grandparent buttons (ie: the big blue 3D-looking ones) are now greyed out when disabled
- Icons on grandparent buttons are now BIG
- Removed user ID from Settings page which shortened the page just enough to get it to fit onto iPad for users with just a few "friends" (users with many friends are assumed to be power users who can handle a bit of scrolling ;) )
- Many font sizes are now responsive to screen width; this is most noticeable when comparing short messages to long messages across mobile/desktop/tablet and also noticeable when looking at a letter in the inbox from a sender with a very long name
- Receiver names are now sorted so they appear in the same order (ABC) every time the user goes to create a post or check on who has viewed it 
- Receiver names are now left justified so they make a neat column

Screenshot 2020-05-28 11 21 22

**[Notes on video]** 
- Video seems to work as well as it ever did but the overall experience for the iPad user is confusing because there is no messaging about wrong filetypes (of the filetypes supported by this app, only .mp4 displays on iPad). There could be better messaging about what types are supported, or additional work to support a wider variety of types (supported types being .ogg, .webm, and .mp4, whereas Apple devices seem to natively produce .mov) 

This is how video looks to the user on iPad when it is an unsupported filetype: 
IMG_0320

This is how video looks on the iPad when it is mp4 filetype:
IMG_0319

**[To do / to test list]**
- I've tested the sent animation on iOS/Safari and MacBook/Chrome, but I'm not sure what it does on other browser combos 

**[More screenshots]**
- I gave up on the centered letters in the inbox, the quantity of media queries and special case code didn't seem worth the trouble when having them left/top justified looks good one every device. If someone feels passionately that the letters need to be centered in the inbox and takes on this work, be sure it looks good in all of the following test cases: 1 letter, 2 letters, 4 letters on iPad landscape and portrait, on mobile in portrait, on desktop at XL, and on desktop at SM or XS. If someone feels passionately that these letters must be centered, and even if the letters are centered (vertically and horizontally) on landscape/iPad, the letters should still appear at the top of the inbox column when in a narrow (phone) resolution (flex-start). Also, when adding a 4th letter, the 4th letter should be left-justified instead of centered in its own row. 

*Four letters before, with centering (before)* I didn't like the large gulf of space between the top row and the bottom row, and I didn't like how the 4th letter appeared in the center instead of at the left position of its row. I was able to get them clustered in the center, but that didn't solve the "4th one is in the middle" problem and it cut the top one in half (like, the top half was outside the inbox container) when viewed on my phone in portrait. 
IMG_0297

*Four letters after, with flex-start alignments and justifications* (this is what's in this PR):
IMG_0304

### CODE REVIEW

**Comment by woodkri** [comment]
I'm not sure if it looks like this on the actual ipad, but on my screen the text is cut off if the post has a photo and text. The video work isn't merged in to this branch but I would guess the same thing happens for video.

cut off text ipad view
cut off text ipad view2

Everything else looks good on my end!

**Comment by RebeccaLyric** [comment]
I like the responsiveness for different screen sizes! The larger buttons are also nice.

I noticed the same thing as Kristin - that some text is cut off if the message has both an image and text. Merging in master should add the code for displaying videos (and remove the console warning about new replies).

A few other small things -- 

Previously when there was a small number of messages in the Inbox they would be centered and justified in the center of the box. It looks like that got lost and if there are few messages they're pushed to the top. It was something I noticed when I had an account with only one message.
Screen Shot 2020-05-26 at 8 42 48 AM

The lighter gray for opened messages looks nice to help distinguish. I have a question about the blue used for the unopened messages (and buttons). Maybe it's just me but in my inbox it looks somewhat out of place? Would it be possible to change to match the color scheme of the header?
Screen Shot 2020-05-26 at 9 18 19 AM

Lastly it looks like there are some console warnings that could be tidied. 

These are all small things but overall this is really nice polishing for the final product!

**Comment by MJGrant** [comment]
I'm going to work through these issues, thanks for trying it out on your own machines. 

@woodkri Whoa, yeah that photo fit + text is not great. I see a very different treatment of photos on my end. Do I not have the latest of something? They look small, but maybe I'm not using the best set of test photos. It might help if I had the same photos you're testing with, if you don't mind sharing them. 

I realized my test case with photo/text was not maximizing the text length. My test case was full of natural text, but that wasn't catching the worst case, so here is the worst case I can come up with - a tall photo with 400 characters, almost all W's, and a ____P at the end so I can identify if the end is actually showing or not. To fit this, I had to adjust the font size to 1.2rem, which I think is rather small, but unless we give the text more space I don't know what else to do for it. 

IMG_0260

**Comment by MJGrant** [comment]
@RebeccaLyric 

I added a commit that should center them. (Sorry for removing it, I did not realize the centering was an intentional/desired effect.) 

Here's a sampling of how it looks with a variety of letter counts and opened/closed letters on iPad. 

IMG_0262
IMG_0268
IMG_0264
IMG_0265
IMG_0266
IMG_0263

**Comment by MJGrant** [comment]
@RebeccaLyric App-wide color palette work should be in its own branch separate from iPad fit issues. No one's really worked on the app's color palette design so we're just seeing a lot of default colors from Material UI. 

If there's time in the final week I'll do a quick pass on it, but it's up for grabs if you want to take ownership earlier than that.

**Comment by MJGrant** [comment]
Just so it's documented on the PR, I did try to repro the image+text=overflow! problem on the iPad and was not able to. These are some of the test cases I tried:

IMG_0270
IMG_0271
IMG_0272

**Pull request merged**
